Add Liberty Prime
JOBBIN9422/TerminusDotNET pull request #35
Opened 2020-12-05 22:57 UTC by MichaelHHall

This PR adds the functionality for Terminus to spin up a docker image of liberty prime and run it. It even includes a (untested) functionality to add a branch parameter to make live testing easier. 

The one caveat to this PR is that whenever terminus has to rebuild the docker image (any time there is a new commit to master, or any time the local liberty repo on terminus box has uncommitted changes), the rebuild takes about 15 minutes. During this 15 minutes Terminus actually disconnected from discord and went offline. He then reconnected properly when the command finished, but it was still strange. If this is unacceptable to you, don't merge and one or both of us can look into a fix on the c# side.

As an aside, I think the next thing I'm gonna do is work on streamlining the docker build process by creating a base dependency image and only rebuilding that when there's been a dependency change (should be very infrequent) and then using that as the base for the actual liberty image. I think this remove the disconnection problem except when rebuilding the dependencies. But that's all on the liberty end, so merge at your own discretion!

2020-12-08 17:40 UTC, JOBBIN9422 requested changes

2020-12-08 17:40 UTC, JOBBIN9422 commented on Modules/LibertyModule.cs
> +            Process p = Process.Start(psi);
wrap processes in `using` statement (e.g. `using (Process p = Process.Start(psi)) { ... }`)

2020-12-08 17:40 UTC, JOBBIN9422 commented on Modules/LibertyModule.cs
> +            Process p = Process.Start(psi);
ditto, wrap process in `using` statement

2021-02-21 04:26 UTC, ct-bess commented
Any update on this?

2021-02-22 15:19 UTC, merged

2021-02-22 15:36 UTC, ct-bess commented
SHUCKS DANG THNX